# Generated by Django 3.1.5 on 2021-09-12 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_remove_createsupplier_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('itemPrice', models.PositiveIntegerField(default=1)),
                ('quantity', models.IntegerField(default=1)),
                ('totalPrice', models.IntegerField(default=1)),
                ('inventoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasesupplier', to='inventory.createsupplier')),
            ],
        ),
    ]
