# Generated by Django 3.1.5 on 2021-09-12 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_createsupplier_username'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('itemPrice', models.PositiveIntegerField(default=1)),
                ('quantity', models.IntegerField(default=1)),
                ('totalPrice', models.IntegerField(default=1)),
                ('phone', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('gstinNo', models.CharField(blank=True, max_length=250, unique=True)),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
    ]
