# Generated by Django 3.1.5 on 2021-09-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_salesitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='gstinNo',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
