# Generated by Django 3.1.5 on 2021-09-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createsupplier',
            name='username',
        ),
    ]
