# Generated by Django 3.1.5 on 2021-09-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_createsupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createsupplier',
            name='gstinNo',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
